
if(LOSCFG_ARCH_FPU_DISABLE)
    list(APPEND LITEOS_CMACRO LOSCFG_ARCH_FPU_DISABLE)
elseif(LOSCFG_ARCH_FPU_VFP_D16)
    list(APPEND LITEOS_CMACRO LOSCFG_ARCH_FPU_VFP_D16)
endif()

list(APPEND LITEOS_INCLUDE    "${CMAKE_SOURCE_DIR}/arch/arm/cortex_m/include")
list(APPEND LITEOS_CXXINCLUDE "${CMAKE_SOURCE_DIR}/arch/arm/cortex_m/include")
