if(LOSCFG_ARCH_ARM_AARCH32)
    include(${CMAKE_SOURCE_DIR}/arch/arm/cpu.cmake)
elseif(LOSCFG_ARCH_ARM_AARCH64)
    include(${CMAKE_SOURCE_DIR}/arch/arm64/cpu.cmake)
elseif(LOSCFG_ARCH_XTENSA)
    include(${CMAKE_SOURCE_DIR}/arch/xtensa/cpu.cmake)
elseif(LOSCFG_ARCH_RISCV)
    include(${CMAKE_SOURCE_DIR}/arch/riscv/cpu.cmake)
else()
    message(FATAL_ERROR "cpu arch not implement !")
endif()
